// <auto-generated />
using System;
using FloorPlan.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FloorPlan.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910153000_AddBuildingBoundaryJson")]
    partial class AddBuildingBoundaryJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("FloorPlan.Api.Data.DoorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BboxX1")
                        .HasColumnType("REAL");

                    b.Property<double?>("BboxX2")
                        .HasColumnType("REAL");

                    b.Property<double?>("BboxY1")
                        .HasColumnType("REAL");

                    b.Property<double?>("BboxY2")
                        .HasColumnType("REAL");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<int>("FloorPlanRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PolygonJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Room1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Room2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceElementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FloorPlanRevisionId");

                    b.HasIndex("Room1Id");

                    b.HasIndex("Room2Id");

                    b.ToTable("Doors");
                });

            modelBuilder.Entity("FloorPlan.Api.Data.FloorPlanEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeightPixels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WidthPixels")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FloorPlans");
                });

            modelBuilder.Entity("FloorPlan.Api.Data.FloorPlanMeasurementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActualDistance")
                        .HasColumnType("REAL");

                    b.Property<double>("EndX")
                        .HasColumnType("REAL");

                    b.Property<double>("EndY")
                        .HasColumnType("REAL");

                    b.Property<int>("FloorPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MetresPerPixel")
                        .HasColumnType("REAL");

                    b.Property<double>("StartX")
                        .HasColumnType("REAL");

                    b.Property<double>("StartY")
                        .HasColumnType("REAL");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FloorPlanId");

                    b.ToTable("FloorPlanMeasurements");
                });

            modelBuilder.Entity("FloorPlan.Api.Data.FloorPlanRevisionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BasedOnRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuildingBoundaryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FloorPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasBathroom")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasKitchen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Valid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FloorPlanId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("FloorPlanRevisions");
                });

            modelBuilder.Entity("FloorPlan.Api.Data.OpeningEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BboxX1")
                        .HasColumnType("REAL");

                    b.Property<double?>("BboxX2")
                        .HasColumnType("REAL");

                    b.Property<double?>("BboxY1")
                        .HasColumnType("REAL");

                    b.Property<double?>("BboxY2")
                        .HasColumnType("REAL");

                    b.Property<int>("FloorPlanRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PolygonJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Room1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Room2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceElementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FloorPlanRevisionId");

                    b.HasIndex("Room1Id");

                    b.HasIndex("Room2Id");

                    b.ToTable("Openings");
                });

            modelBuilder.Entity("FloorPlan.Api.Data.RoomEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AreaPixels")
                        .HasColumnType("REAL");

                    b.Property<double?>("AreaSquareMetres")
                        .HasColumnType("REAL");

                    b.Property<double>("CentroidX")
                        .HasColumnType("REAL");

                    b.Property<double>("CentroidY")
                        .HasColumnType("REAL");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<int>("FloorPlanRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PolygonJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceElementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FloorPlanRevisionId", "SourceElementId")
                        .IsUnique();

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("FloorPlan.Api.Data.WindowEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BboxX1")
                        .HasColumnType("REAL");

                    b.Property<double?>("BboxX2")
                        .HasColumnType("REAL");

                    b.Property<double?>("BboxY1")
                        .HasColumnType("REAL");

                    b.Property<double?>("BboxY2")
                        .HasColumnType("REAL");

                    b.Property<int>("FloorPlanRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PolygonJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceElementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FloorPlanRevisionId");

                    b.ToTable("Windows");
                });

            modelBuilder.Entity("FloorPlan.Api.Data.DoorEntity", b =>
                {
                    b.HasOne("FloorPlan.Api.Data.FloorPlanRevisionEntity", "Revision")
                        .WithMany("Doors")
                        .HasForeignKey("FloorPlanRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FloorPlan.Api.Data.RoomEntity", "Room1")
                        .WithMany()
                        .HasForeignKey("Room1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FloorPlan.Api.Data.RoomEntity", "Room2")
                        .WithMany()
                        .HasForeignKey("Room2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Revision");

                    b.Navigation("Room1");

                    b.Navigation("Room2");
                });

            modelBuilder.Entity("FloorPlan.Api.Data.FloorPlanMeasurementEntity", b =>
                {
                    b.HasOne("FloorPlan.Api.Data.FloorPlanEntity", "FloorPlan")
                        .WithMany("Measurements")
                        .HasForeignKey("FloorPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FloorPlan");
                });

            modelBuilder.Entity("FloorPlan.Api.Data.FloorPlanRevisionEntity", b =>
                {
                    b.HasOne("FloorPlan.Api.Data.FloorPlanEntity", "FloorPlan")
                        .WithMany("Revisions")
                        .HasForeignKey("FloorPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FloorPlan");
                });

            modelBuilder.Entity("FloorPlan.Api.Data.OpeningEntity", b =>
                {
                    b.HasOne("FloorPlan.Api.Data.FloorPlanRevisionEntity", "Revision")
                        .WithMany("Openings")
                        .HasForeignKey("FloorPlanRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FloorPlan.Api.Data.RoomEntity", "Room1")
                        .WithMany()
                        .HasForeignKey("Room1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FloorPlan.Api.Data.RoomEntity", "Room2")
                        .WithMany()
                        .HasForeignKey("Room2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Revision");

                    b.Navigation("Room1");

                    b.Navigation("Room2");
                });

            modelBuilder.Entity("FloorPlan.Api.Data.RoomEntity", b =>
                {
                    b.HasOne("FloorPlan.Api.Data.FloorPlanRevisionEntity", "Revision")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorPlanRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("FloorPlan.Api.Data.WindowEntity", b =>
                {
                    b.HasOne("FloorPlan.Api.Data.FloorPlanRevisionEntity", "Revision")
                        .WithMany("Windows")
                        .HasForeignKey("FloorPlanRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revision");
                });

            modelBuilder.Entity("FloorPlan.Api.Data.FloorPlanEntity", b =>
                {
                    b.Navigation("Measurements");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("FloorPlan.Api.Data.FloorPlanRevisionEntity", b =>
                {
                    b.Navigation("Doors");

                    b.Navigation("Openings");

                    b.Navigation("Rooms");

                    b.Navigation("Windows");
                });
#pragma warning restore 612, 618
        }
    }
}
